/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xl;

import org.junit.Test;

import xl.expr.XLModel;
import xl.expr.XLTreeModel;
import xl.util.XLCircularException;
import xl.util.XLException;

import static org.junit.Assert.*;

public class AppTest {
    
    @Test 
    public void circularityTest() {
        XLModel model = new XLTreeModel(3, 3); 

        assertThrows(XLCircularException.class, () -> {
            model.setCell("A1", "A2");
            model.setCell("A2", "A3");
            model.setCell("A3", "A1");
        });

        assertThrows(XLCircularException.class, () -> {
            model.setCell("A1", "A2");
            model.setCell("A2", "A1");
        });
    }

    @Test
    public void syntaxErrorTest() {
        XLModel model = new XLTreeModel(3, 3); 

        assertThrows(XLException.class, () -> model.setCell("A1", "fgchvbjk"));
        assertThrows(XLException.class, () -> model.setCell("A1", "?"));
        assertThrows(XLException.class, () -> model.setCell("A1", " "));
    }
}
