/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xl;

import java.io.IOException;

import xl.expr.XLModel;
import xl.expr.XLTreeModel;
import xl.gui.XL;
import xl.gui.XLCounter;
import xl.gui.XLList;
import xl.util.XLCircularException;
import xl.util.XLException;

public class App {
    
    public static void main(String[] args) {
        new App().run();
    }

    public void run() {
        // var xl = new XL(new XLList(), new XLCounter());
        // xl.rename("XL");

        // XLModel model = modelTest(); 
        // guiTest(model);
        guiTest2();
    }

    /**
     *  TODO: remove in final launch
     */ 
    private XLModel modelTest() {
        XLModel model = new XLTreeModel(3, 3); 

        try {
            model.setCell("A1", "1+2");
            model.setCell("A2", "A1"); 
            model.setCell("A3", "A1+A2");
            model.setCell("B1", "#hej"); 
            model.setCell("B2", "#x =");
            model.setCell("B3", "");
        } catch (XLException | XLCircularException | IOException e) {
            e.printStackTrace();
        }

      /*  var vals = model.getValues(); 
        for (var entry : vals.entrySet()) {
            System.out.println(entry); 
        } */

        System.out.printf("%s = %s", "B1", model.getExpression("B1"));
        return model; 
    }

    private void guiTest(XLModel model) {
        new XL(new XLList(), new XLCounter(), model).updateView();
    }

    private void guiTest2() {
        new XL(new XLList(), new XLCounter()).updateView();
    }
}
